name: Docker

on:
  push:
    branches:
    - main

jobs:
  Build:
    runs-on: macos-latest
    steps:
    - name: Publish Docker Action
      uses: jerray/publish-docker-action@v1.0.5
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    
