name: Pull-Request-Manager

on : pull_request

jobs:

 Approve-Request:
   runs-on: ubuntu-latest
   steps:
   - name: Auto Approve 1
     uses: juliangruber/approve-pull-request-action@v1
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       number: 1
       
   - name: Auto Approve 2
     uses: hmarr/auto-approve-action@v2.1.0
     with:
      # The GITHUB_TOKEN secret
      github-token: ${{ secrets.GITHUB_TOKEN }}

 Merge-Branch:
  runs-on : ubuntu-latest
  steps:
   - name: Merge Pull Request
   # You may pin to the exact commit or the version.
   # uses: maxkomarychev/oction-merge-pull-request@ba8abd4e2a7776b2d973e088156ea69ac99c30d3
     uses: maxkomarychev/oction-merge-pull-request@v0.7.1
     with:
       token: ${{ secrets.GITHUB_TOKEN }}

