name: Pull-Request-Manager

on : pull_request

jobs:

 Approve-Request:
   runs-on: ubuntu-latest
   steps:
   - name: Auto Approve 1
     uses: juliangruber/approve-pull-request-action@v1
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       number: 1
       
   - name: Auto Approve 2
     uses: hmarr/auto-approve-action@v2.1.0
     with:
      # The GITHUB_TOKEN secret
      github-token: ${{ secrets.GITHUB_TOKEN }}

 Merge-Branch:
  runs-on : ubuntu-latest
  steps:
   - name: Merge Pull Request
  # You may pin to the exact commit or the version.
  # uses: juliangruber/merge-pull-request-action@d407bf625e1ceb819fa7cc531929bd3bbe641698
     uses: juliangruber/merge-pull-request-action@v1.0.0
     with:
       # GitHub Token
       github-token:  ${{ secrets.GITHUB_TOKEN }}
       # Pull Request number
       number: 1

